# Generated by Django 3.1.1 on 2020-09-24 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('find_bus_congestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buslist',
            options={'managed': True},
        ),
    ]
