# Generated by Django 3.1.1 on 2020-09-24 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('find_bus_congestion', '0002_auto_20200924_2009'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FindBusCongestionBusList',
        ),
    ]
