# Generated by Django 3.1.1 on 2020-09-24 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_bus_congestion', '0003_delete_findbuscongestionbuslist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buslist',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
