# Generated by Django 3.1.1 on 2020-09-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_bus_congestion', '0004_auto_20200924_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerminalList',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('terminal', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'terminal_list',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='buslist',
            options={'managed': False},
        ),
    ]
